---
- name: Install Prometheus on Amazon Linux 2
  hosts: all
  become: yes
  tasks:
    - name: Update yum packages
      yum:
        name: '*'
        state: latest
    - name: Install dependencies
      yum:
        name:
          - wget
          - tar
        state: present
    - name: Download Prometheus
      get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v2.30.3/prometheus-2.30.3.linux-amd64.tar.gz
        dest: /tmp/prometheus.tar.gz
    - name: Extract Prometheus
      unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /tmp
        remote_src: yes
    - name: Create Prometheus user
      user:
        name: prometheus
        shell: /sbin/nologin
        create_home: no
    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        owner: prometheus
        group: prometheus
      with_items:
        - /etc/prometheus
        - /var/lib/prometheus
    - name: Move binaries
      copy:
        src: /tmp/prometheus-2.30.3.linux-amd64/{{ item }}
        dest: /usr/local/bin/{{ item }}
        owner: prometheus
        group: prometheus
        mode: '0755'
        remote_src: yes
      with_items:
        - prometheus
        - promtool
    - name: Move configuration files
      copy:
        src: /tmp/prometheus-2.30.3.linux-amd64/prometheus.yml
        dest: /etc/prometheus/prometheus.yml
        owner: prometheus
        group: prometheus
        mode: '0644'
        remote_src: yes
    - name: Setup Prometheus service
      copy:
        content: |
          [Unit]
          Description=Prometheus
          Wants=network-online.target
          After=network-online.target
 
          [Service]
          User=prometheus
          Group=prometheus
          Type=simple
          ExecStart=/usr/local/bin/prometheus \
            --config.file /etc/prometheus/prometheus.yml \
            --storage.tsdb.path /var/lib/prometheus/ \
            --web.console.templates=/usr/local/share/prometheus/consoles \
            --web.console.libraries=/usr/local/share/prometheus/console_libraries
 
          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/prometheus.service
        owner: root
        group: root
        mode: '0644'
    - name: Reload systemd
      command: systemctl daemon-reload
    - name: Enable and start Prometheus service
      systemd:
        name: prometheus
        enabled: yes
        state: started
